BOOTLOADER = $(CS140E_FINAL_PROJ_PATH)/bin/pi-install

PROGS := 0-test-display-send-byte.c

# define this if you need to give the device for your pi
TTYUSB = 

# set RUN = 1 if you want the code to automatically run after building.
RUN = 0

LIB_POST += $(CS140E_2025_PATH)/lib/libgcc.a

include $(CS140E_FINAL_PROJ_PATH)/libpi/mk/Makefile.robust
