BOOTLOADER = $(CS140E_FINAL_PROJ_PATH)/bin/pi-install

COMMON_SRC := i2c.c

PROGS := main.c

# define this if you need to give the device for your pi
TTYUSB = 

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1

include $(CS140E_FINAL_PROJ_PATH)/libpi/mk/Makefile.robust