BOOTLOADER = $(CS140E_FINAL_PROJ_PATH)/bin/pi-install

PROGS := 0-test-draw.c

COMMON_SRC = display.c
STAFF_OBJS = staff-i2c.o

# define this if you need to give the device for your pi
TTYUSB = 

# set RUN = 1 if you want the code to automatically run after building.
RUN = 0

include $(CS140E_FINAL_PROJ_PATH)/libpi/mk/Makefile.robust