BOOTLOADER = my-install

PROGS := hello_world.c

# define this if you need to give the device for your pi
TTYUSB = 

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1

include $(CS140E_2025_PATH)/libpi/mk/Makefile.robust

clean::
	make -C clean