clean:
	make clean -C setup_test
	make clean -C i2c_hack
	make clean -C display-send-byte
	make clean -C fft
	make clean -C adc
	make clean -C multimeter
	make clean -C display_ig
	make clean -C yuchi_intergration
